// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJZFu83p2BXYef1LMGW3sNCTHVo683uzI',
    appId: '1:310154729657:web:250cabd7de6f9a36232368',
    messagingSenderId: '310154729657',
    projectId: 'greezy-3bfb5',
    authDomain: 'greezy-3bfb5.firebaseapp.com',
    storageBucket: 'greezy-3bfb5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgTKXw4iB_sWpXcHIQ4Tw8eAklEaqRme8',
    appId: '1:310154729657:android:6eb6f9004479c653232368',
    messagingSenderId: '310154729657',
    projectId: 'greezy-3bfb5',
    storageBucket: 'greezy-3bfb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBatPxaryzlJFYN3ZBKF6i5KXtDmZJUr10',
    appId: '1:310154729657:ios:7a9a0f92854324ab232368',
    messagingSenderId: '310154729657',
    projectId: 'greezy-3bfb5',
    storageBucket: 'greezy-3bfb5.appspot.com',
    androidClientId: '310154729657-e0tfbqnlebr4vmvcv7k9dqdhben1lbfh.apps.googleusercontent.com',
    iosClientId: '310154729657-l6e343jl8ulpih60crluf714q91b48fa.apps.googleusercontent.com',
    iosBundleId: 'com.morpheus.greezy',
  );
}
